### ISSUE TITLE
Project not distributed via Homebrew since version 0.25.1

### ISSUE THREAD

**Issue by ThomasVitale** [CycloneDX/homebrew-cyclonedx#8]
I followed the installation documentation and got cyclonedx-cli installed on my Linux machine from Homebrew.

`brew install cyclonedx/cyclonedx/cyclonedx-cli`

The version installed is 0.25.1 even though the latest available is 0.27.1.

I can see that no newer versions have been published to the Homebrew Tap since version 0.25.1: https://github.com/CycloneDX/homebrew-cyclonedx

**Comment by jkowalleck** [comment]
Latest versions have been published in this very tap. 
I'd close this ticket and might work on further automation later.
